### Site metadata

# If you don't set these, they will be inferred from the repo's description on GitHub.
title: Jekyll GH Actions Quickstart
description: Starter template for a Jekyll 4 site - deployed with GH Actions and GH Pages

### Build settings

url: https://dplanella.github.io
baseurl: /test-gh-pages-jekyll

# remote_theme: sighingnow/jekyll-gitbook
theme: just-the-docs

plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

defaults:
  - scope:
      path: "*.md"
    values:
      layout: page

exclude:
  - docs/
  - LICENSE
  - Makefile
  - README.md

mermaid:
  # Version of mermaid library
  # Pick an available version from https://cdn.jsdelivr.net/npm/mermaid/
  version: "9.1.7"

color_scheme: primer
